version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_studs
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: grigory
      POSTGRES_PASSWORD: grigory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
